### PR TITLE
Fix issue with MiddleSlash replacer

### PR DESCRIPTION
**Pull request by jairbubbles**
As replacers are applied one after the other, the `/` added from a previous replacer (`NonLeadingSingleStar`) was incorrectly being detected by the `MiddleSlash` replacer and it added a `^` at the beginning of the pattern.

| before | after |
| ------ | ------ |
| `foo*` => `^foo[^/]*(/.*)?$` | `foo*` => `foo[^/]*(/.*)?$` |

### CODE REVIEW

**Review by goelhardik — APPROVED** [review]
Thanks again!

**Comment by jairbubbles** [comment]
Awesome! Could you publish a new version?

I have been looking for a good library for gitignore for a quite time so I was happy to find this one.

I stumbled on https://github.com/markashleybell/MAB.DotIgnore but the behavior differs from the git command line.

I really like that you're testing against `libGit2Sharp` ! It would be even better to test against git command line.

**Comment by goelhardik** [comment]
@jairbubbles it's published `0.1.36`. https://www.nuget.org/packages/Ignore/

Yes I saw that one too, but at that point for some reason I didn't like it. 

I assumed `libGit2Sharp`'s behavior would match git command line. Have you noticed if that's not the case?

**Comment by jairbubbles** [comment]
@goelhardik For the `.gitignore` rules I can't tell but we stoppped using the status computing from libgit2sharp in favor of using git status directly.

**Pull request merged**
