### PR TITLE
Escape dots in the beginning

### PR DESCRIPTION
**Pull request by goelhardik**
`*.mm.*` -> `.*\.mm\.[^/]*(/.*)?$`

### CODE REVIEW

**Comment by jairbubbles** [comment]
I was about to send a PR that fixes it... 🤦

**Comment by goelhardik** [comment]
> I was about to send a PR that fixes it... 🤦

Lol sorry I saw you created an issue and I had some time. Let's assign issues next time so we know who's working on it.

**Comment by jairbubbles** [comment]
FYI I created a PR on git repository as I think there's a typo in the documentation => https://github.com/git/git/pull/972.

(The contribution process is very complicated on this repository 😣)

**Comment by goelhardik** [comment]
Oh nice.

**Pull request merged**
